# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x05model\"\x0f\n\rHealthRequest\"1\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\"\x1f\n\x0ePredictRequest\x12\r\n\x05input\x18\x01 \x01(\t\"9\n\x0fPredictResponse\x12\x12\n\nprediction\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x32\x7f\n\x0cModelService\x12\x35\n\x06health\x12\x14.model.HealthRequest\x1a\x15.model.HealthResponse\x12\x38\n\x07predict\x12\x15.model.PredictRequest\x1a\x16.model.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=22
  _globals['_HEALTHREQUEST']._serialized_end=37
  _globals['_HEALTHRESPONSE']._serialized_start=39
  _globals['_HEALTHRESPONSE']._serialized_end=88
  _globals['_PREDICTREQUEST']._serialized_start=90
  _globals['_PREDICTREQUEST']._serialized_end=121
  _globals['_PREDICTRESPONSE']._serialized_start=123
  _globals['_PREDICTRESPONSE']._serialized_end=180
  _globals['_MODELSERVICE']._serialized_start=182
  _globals['_MODELSERVICE']._serialized_end=309
# @@protoc_insertion_point(module_scope)
